identifier: l6w7i6te67jeqco2
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: blog
homeFolder: C:\Users\Samsung\source\Angular\AngularExperiment\blog
distFolder: dist/blog
outDir: C:\Users\Samsung\source\Angular\AngularExperiment\blog\dist\static
handle404: ''
allowErrorCollect: true
